# =========================================================
# SISTEMA DE BACKUP AUTOMATIZADO - PROJETO MONITORAMENTO
# =========================================================
# Descrição: Sistema de backup diário automatizado para configurações
#            e dados do projeto Monitoramento (GLPI, Zabbix, Grafana)
# Frequência: Diária (24h)
# Retenção: 30 dias
# Formato: .tar.gz compactado
# Localização: /mnt/backup/monitoramento/
# Conteúdo: Volumes Docker dos serviços de monitoramento
# =========================================================

services:
  backup-monitoramento:
    image: alpine:latest
    container_name: backup-monitoramento
    restart: unless-stopped
    
    # Configurações de timezone
    environment:
      - TZ=America/Sao_Paulo
      - BACKUP_INTERVAL=86400  # 24 horas em segundos
      - BACKUP_RETENTION=30    # Manter backups por 30 dias
      - PROJECT_NAME=monitoramento
    
    # Mapeamento de volumes
    volumes:
      # Volumes dos serviços (somente leitura para backup)
      - glpi_db_data:/backup/source/glpi_db_data:ro
      - glpi_files:/backup/source/glpi_files:ro
      - zabbix_db_data:/backup/source/zabbix_db_data:ro
      - grafana_data:/backup/source/grafana_data:ro
      
      # Diretório de destino dos backups
      - /mnt/backup/monitoramento:/backup/destination
      
      # Script opcional (removido: arquivo ausente)
    
    # Comando de inicialização
    command: >
      sh -c "
        echo '=== SISTEMA DE BACKUP MONITORAMENTO INICIADO ===' &&
        echo 'Projeto: Monitoramento (GLPI + Zabbix + Grafana)' &&
        echo 'Frequência: Diária (24h)' &&
        echo 'Retenção: 30 dias' &&
        echo 'Destino: /mnt/backup/monitoramento/' &&
        echo '=================================================' &&
        
        # Instalar dependências
        apk add --no-cache tar gzip coreutils findutils &&
        
        # Criar diretório de backup se não existir
        mkdir -p /backup/destination &&
        
        # Loop infinito para backups periódicos
        while true; do
          echo '' &&
          echo '[$(date)] === INICIANDO BACKUP MONITORAMENTO ===' &&
          
          # Definir nome do arquivo de backup
          BACKUP_DATE=$(date +%Y%m%d_%H%M%S) &&
          BACKUP_FILE=\"monitoramento_backup_$${BACKUP_DATE}.tar.gz\" &&
          BACKUP_PATH=\"/backup/destination/$${BACKUP_FILE}\" &&
          
          echo '[$(date)] Criando backup: $${BACKUP_FILE}' &&
          
          # Criar backup compactado
          cd /backup/source &&
          if [ -d glpi_db_data ] && [ -d glpi_files ] && [ -d zabbix_db_data ] && [ -d grafana_data ]; then
            tar -czf \"$${BACKUP_PATH}\" \
              glpi_db_data/ \
              glpi_files/ \
              zabbix_db_data/ \
              grafana_data/ \
              2>/dev/null
          else
            echo '[$(date)] ⚠️ AVISO: Alguns volumes não estão disponíveis. Criando backup dos volumes existentes...' &&
            tar -czf \"$${BACKUP_PATH}\" \
              $(find . -maxdepth 1 -type d -name '*data*' -o -name '*files*' 2>/dev/null | head -10) \
              2>/dev/null || echo '[$(date)] ℹ️ Backup vazio criado (volumes não populados)'
          fi &&
          
          # Verificar se o backup foi criado com sucesso
          if [ -f \"$${BACKUP_PATH}\" ]; then
            BACKUP_SIZE=$(du -h \"$${BACKUP_PATH}\" | cut -f1) &&
            echo '[$(date)] ✅ Backup criado com sucesso!' &&
            echo '[$(date)] 📁 Arquivo: $${BACKUP_FILE}' &&
            echo '[$(date)] 📊 Tamanho: $${BACKUP_SIZE}' &&
            
            # Verificar integridade do backup
            echo '[$(date)] 🔍 Verificando integridade...' &&
            if tar -tzf \"$${BACKUP_PATH}\" >/dev/null 2>&1; then
              echo '[$(date)] ✅ Integridade verificada com sucesso!' &&
              
              # Remover backups antigos (manter apenas os últimos 30 dias)
              echo '[$(date)] 🧹 Removendo backups antigos...' &&
              find /backup/destination -name \"monitoramento_backup_*.tar.gz\" -type f -mtime +$${BACKUP_RETENTION} -delete &&
              
              # Contar backups restantes
              BACKUP_COUNT=$(find /backup/destination -name \"monitoramento_backup_*.tar.gz\" -type f | wc -l) &&
              echo '[$(date)] 📈 Total de backups mantidos: $${BACKUP_COUNT}' &&
              echo '[$(date)] ✅ Backup concluído com sucesso!' &&
              echo '[$(date)] ⏰ Próximo backup em: $${BACKUP_INTERVAL} segundos (24h)'
            else
              echo '[$(date)] ❌ ERRO: Backup corrompido detectado!' &&
              rm -f \"$${BACKUP_PATH}\" &&
              echo '[$(date)] 🗑️ Backup corrompido removido'
            fi
          else
            echo '[$(date)] ❌ ERRO: Falha ao criar backup!'
          fi &&
          
          echo '[$(date)] === BACKUP MONITORAMENTO FINALIZADO ===' &&
          echo '' &&
          
          # Aguardar próximo ciclo
          sleep $${BACKUP_INTERVAL}
        done
      "
    
    # Health check
    healthcheck:
      test: ["CMD", "sh", "-c", "find /backup/destination -name 'monitoramento_backup_*.tar.gz' -mtime -2 | grep -q ."]
      interval: 1h
      timeout: 30s
      retries: 3
      start_period: 5m
    
    # Rede compartilhada
    networks:
      - itsm_shared_net
    
    # Labels para organização
    labels:
      - "com.projeto.monitoramento.backup=true"
      - "com.projeto.monitoramento.service=backup"
      - "com.projeto.monitoramento.version=1.0"

# Definir volumes externos (referenciando os volumes dos serviços)
volumes:
  glpi_db_data:
  glpi_files:
  zabbix_db_data:
  grafana_data:

networks:
  itsm_shared_net:
    external: true
